inherit_gem:
  onkcop:
    - "config/rubocop.yml"
    # uncomment if use rails cops
    # - "config/rails.yml"
    # uncomment if use rspec cops
    # - "config/rspec.yml"

AllCops:
  TargetRubyVersion: 2.3

# Offense count: 1
# Cop supports --auto-correct.
Metrics/BlockLength:
  Exclude:
    - 'lib/capistrano/tasks/unicorn.rb'
    - 'spec/controllers/admin/users_controller_spec.rb'
    - 'spec/factories/letters.rb'
    - 'spec/models/letter_spec.rb'
    - 'spec/models/user_spec.rb'
    - 'spec/models/user_spec.rb'
Metrics/LineLength:
  Exclude:
    - 'Guardfile'
    - 'spec/support/controller_macros.rb'
Metrics/MethodLength:
  Exclude:
    - 'app/models/book.rb'
Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/admin/reports_controller.rb'
    - 'app/controllers/admin/users_controller.rb'
    - 'app/controllers/letters/popular_controller.rb'
Style/GuardClause:
  Exclude:
    - 'app/models/book.rb'
Style/IdenticalConditionalBranches:
  Exclude:
    - 'app/controllers/storages_controller.rb'
