default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: pic_development

test:
  <<: *default
  database: pic_test

production:
  <<: *default
  database: pic_production
  username: root
  password: 
  socket: /var/lib/mysql/mysql.sock
